eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 5555

zuul:
  routes:
    customer:
      path: /customer/**
      serviceId: customer-service
      stripPrefix: false
    product:
      path: /product/**
      serviceId: product-service
      stripPrefix: false
    sale:
      path: /sale/**
      serviceId: sale-service
      stripPrefix: false
    oauth:
      path: /oauth/**
      serviceId: oauth-service
      stripPrefix: false

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:7777/user